version: "2"
services:
  db:
    image: postgres:alpine
    env_file:
      - test.env
  api:
    image: librarian:dev
    command: pytest -x
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./:/usr/local/src/"
    env_file:
      - test.env